AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
    ModelBucketName:
        Type: String
        Default: 'witchbooru-model'
    NeuralNetNumChunks:
        Type: Number
        Default: 4

Resources:
    WitchbooruApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            BinaryMediaTypes: ['*~1*']

    WitchbooruFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: provided
            Handler: witchbooru.bootstrap
            PackageType: Zip
            CodeUri: ./lambda.zip
            Timeout: 30
            MemorySize: 2048
            Tracing: Active
            Environment:
                Variables:
                    BUCKET_NAME: !Ref ModelBucketName
                    NEURAL_NET_NUM_CHUNKS: !Ref NeuralNetNumChunks
            Events:
                WitchbooruGet:
                    Type: Api
                    Properties:
                        Path: /
                        Method: get
                        RestApiId:
                            Ref: WitchbooruApi
                WitchbooruPost:
                    Type: Api
                    Properties:
                        Path: /
                        Method: post
                        RestApiId:
                            Ref: WitchbooruApi
            Policies:
                - S3ReadPolicy:
                      BucketName: !Ref ModelBucketName

Outputs:
    WitchbooruApi:
        Value: !Sub 'https://${WitchbooruApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    WitchbooruFunction:
        Value: !GetAtt WitchbooruFunction.Arn
    WitchbooruFunctionIamRole:
        Value: !GetAtt WitchbooruFunctionRole.Arn
