name: build

on: [push, pull_request, workflow_dispatch]

jobs:
    build-backend:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-20.04]
                rust: [stable, beta, nightly]
                include:
                    - os: macos-10.15
                      rust: stable
                    - os: windows-2019
                      rust: stable
        steps:
            - uses: actions/checkout@v2
            - uses: hecrj/setup-rust-action@v1
              with:
                  rust-version: ${{ matrix.rust }}
                  components: rustfmt, clippy
            - run: cargo build --workspace --verbose
            - run: cargo test --workspace --verbose
            - run: cargo fmt --all -- --check
            - run: cargo clippy --workspace -- -D warnings

    build-frontend:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v2
            - run: npm ci
            - run: npm run lint
            - run: npm run checkfmt
            - run: npm run build
